### ISSUE TITLE
StaticFileRouteHandler missing ContentType for various filetypes

### ISSUE THREAD

**Issue by naice** [tomkuijsten/restup#38]
If i run the WebServer on my PI with latest Win IOT Core release I get empty ContentType e.g. for .html files or .js files. This will cause the website to not display correctly in chrome and firefox, however edge will display the side correctly and so does the WebView control (win uwp).

**Comment by Jark** [comment]
Hello naice,

I suspect the pi is not correctly giving back the content type for the extension and there might need to be a change in: https://github.com/tomkuijsten/restup/blob/master/src/WebServer/File/StaticFileRouteHandler.cs#L82 to fall back on a predefined list of extension to mime types or use the predefined list of extension -> mime types and fall back on the content type that uwp reports.

I've got some spare time tonight to run it on an actual pi so can take a look at it then, I suspect the fix will be quite simple, or alternatively you can put a fix in if you want?

**Comment by naice** [comment]
atm i am working on a fix for it. The error occurs on exactly at this function. I will give a shout if i got an reasonable solution for this.

**Comment by naice** [comment]
I created a fix. #39

**Comment by tomkuijsten** [comment]
Thanks for the fix, just merged it.

**Comment by naice** [comment]
(Y)
Am 08.03.2016 3:13 nachm. schrieb "Tom Kuijsten" <notifications@github.com>:

**Comment by Jark** [comment]
Hey @naice ,

Thanks for doing the work, much appreciated!

I was half way through writing this when @tomkuijsten approved the merge request, but don't want to let it go to waste so here goes:

- what do you guys think of getting rid off IsOverrideEnabled on MimeTypes? I think we should just default to the list of mime types that is specified, and only go for the ms content type if we don't know about it. More choice leads to more complexity and global variables are best to avoid.

- I would add an Extension or Name property on IFile so we don't have to pass meta information on the [GetHttpResponse](https://github.com/naice/restup/commit/aab5c3d7ff83e03fa35eac9597702591ca4e7473#diff-9624b799d8fb6a1facedb2f2820acf13R82) call

- I think MimeTypes should be exposed as IReadOnlyDictionary<string, string> so that we can assume it's thread safe and it won't cause problems if someone decides to add / remove mime types during serving file requests

-we should probably add some unit tests around the added functionality

I don't mind implementing the above if you don't want / don't have the time for it. 

Cheers,

Jark

**Comment by naice** [comment]
Making the list read-only will cause Users to not be able to insert their
own Mime types. I think that's a huge loss of functionality
Am 08.03.2016 3:32 nachm. schrieb "Jark" <notifications@github.com>:

**Comment by Jark** [comment]
I'm not against allowing users to add to the mime types list, but exposing an interface that allows users to do this during execution is dangerous and can lead to subtle bugs / crashes of the server.

I can see a couple of ways to fix this:

1. expose methods on MimeTypes (and maybe rename it to MimeTypeProvider or something) that allows users to add / remove from it in a thread safe way.

2. or, and this is the option I prefer, we can allow users of the api to pass the mime types / modify them during construction of the static file route handler.

The reason I prefer option nr. 2 is that I think that 99% of the users will not want/need to modify their mime types.

**Comment by naice** [comment]
I like the idea of passing the mimetypes throug construction of the
StaticFileRouteHandler but from Users View i like to have Software that
runs as installed and since its a server for uwp i think it will be used a
lot of ppl who run it on a pi like me. Why should they bother about the
mimetypes if we already got a solution for this? Maybe i don't understand
you? But for today I need to play the division!

I have created another pull req with a threadsafe solution for now :)
Am 08.03.2016 4:03 nachm. schrieb "Jark" <notifications@github.com>:

**Comment by Jark** [comment]
Exactly my point naice, so we should fall back to a sensible default.

I created a pull request as well, with unit tests and by adding the ability to specify the mime types if you really need to. If this situation turns out to be fairly common we can create something around it to make it easier.

Pull request can be found here: https://github.com/tomkuijsten/restup/pull/41.
