### ISSUE TITLE
can't visit HeadedDemo from a remote machine through web browser

### ISSUE THREAD

**Issue by liudanking** [tomkuijsten/restup#52]
I follow the wiki, and all work well.
Then I launch HeadedDemo on machine A, and I can get response from HeadedDemo UI.
But when I try to visit HeadedDemo from machine B with Chrome, I can't get any response.
I have checked:
1. Machine A and B are in same LAN;
2. Firewall of machine A is off.

**Comment by Jark** [comment]
Hi liudanking,

Are you running the HeadedDemo app from windows 10 on a pc from within visual studio? If so, you might run into http.sys uac permissioning issues. 

Can you try running the HeadedDemo in visual studio in administrator mode and trying again? If that works then you might have to use netsh to add a port reservation for the app.

Let me know how you get on and if you have any questions, I'll try and add a wiki page about this sometime this week as well.

Cheers,

Jark

**Comment by liudanking** [comment]
@Jark 
In the manifest I checked **"Private Networks (Client & Server)"**, and it works now.

**Comment by Jark** [comment]
Hi @liudanking,

Glad it's now working for you.

The HeadedDemo should however work out of the box as **"Private Networks (Client  & Server)" is specified in the application manifest -> https://github.com/tomkuijsten/restup/blob/master/src/HeadedDemo/Package.appxmanifest#L27.

Did you happen to copy the HeadedDemo files into a new project?

**Comment by liudanking** [comment]
@Jark I did not copy that file to new project.
I think **<Capability Name="internetClientServer" />** and **<Capability Name="privateNetworkClientServer" />** have different capability. I just find that if I want to visit HeadedDemo from another machine, I must add **<Capability Name="privateNetworkClientServer" />**.

**Comment by tomkuijsten** [comment]
Looks like this issue can be closed, correct?

**Comment by liudanking** [comment]
Yes :)

**Comment by tomkuijsten** [comment]
Just reading it again and didn't initially see the difference between Internet (Client & Server) and Private Networks (Client & Server). The latter is not enabled in the demo projects and according to this issue it should be, am I correct?

**Comment by liudanking** [comment]
Yes

**Comment by Jark** [comment]
Yup, this is why I didn't close it yet, I thought I would have time last night to do the change.

I was going to to add that capability to the demo projects just to make sure it works on Windows 10 systems when tried over a local network.

See: https://msdn.microsoft.com/en-us/library/windows/apps/br211423.aspx

The description at `privateNetworkClientServer` says: "On Windows Phone, provides the same access as internetClient or internetClientServer." Which is why it's probably not necessary for Windows 10 IOT.

@tomkuijsten do you want to make the change? If not I can do it.
