### ISSUE TITLE
Need access to incoming request headers

### ISSUE THREAD

**Issue by clough42** [tomkuijsten/restup#67]
I'm trying to do HMAC-based authorization of incoming requests, and to do this, I need to be able to read the request headers.  I see in the implementation docs that there should be an attribute to do this (FromBody), but I don't see it in the code anywhere?

Am I missing something obvious?

**Comment by stevegg** [comment]
Yeah, it'd be great if there was a way to inject the actual HttpServerRequest.  This would nicely get around the problem of matching query parameters by allowing the user to add code in the controller to get parameter values from the request.

**Comment by tomkuijsten** [comment]
@clough42 the ```FromBody``` is used to fill your parameter with data from the http body. If you send some json data with your http request, it will get deserialized and provided as the ```FromBody``` parameter.

I like the idea of some more control over headers in your request/response chain. Would be quite easy to inject it in your controller method. We could search for a parameter of type ```HttpServerRequest``` and send it with the other parameter values, eg:

``` cs
[UriFormat("/simpleparameter/{id}")]
public IGetResponse GetWithServerRequest(int id, [FromBody]MyType complexObject, HttpServerRequest request)
```

**Comment by Jark** [comment]
Exposing the whole request in the method to solve HMAC authorisation seems a bit like a hack to me, I don't think you want to deal with authorisation based things in the controllers themselves, but it should be handled outside. I'm wondering if it would be a good idea to implement Authorization header support to solve this issue. 

@clough42 do you require hmac to be done by using the Authorization header?
Doc: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.8

I think there are a couple of ways we could go about implementing it and it all depends on the use case. 

1. On both the RestHandler and the FileHandler we add an option to add a authorisation handler which has an interface like:

```
interface IPrincipal { }
internal class AnonymousPrincipal : IPrincipal { }
internal class AuthorisationPrincipal : IPrincipal
{
    public string AuthorisationHeaderValue { get; }

    public AuthorisationPrincipal(string authorisationHeaderValue)
    {
        AuthorisationHeaderValue = authorisationHeaderValue;
    }
}
    
internal class Claim 
{
    public string PathToControllerAndMethod { get; }

    public Claim(string pathToControllerAndMethod)
    {
        PathToControllerAndMethod = pathToControllerAndMethod;
    }
}

internal interface IAuthorisationManager
{
    bool IsAuthorised(Claim claim, IPrincipal principal);
}

sealed class AuthorisationHandler 
{
    private readonly IAuthorisationManager manager;

    public AuthorisationHandler(IAuthorisationManager manager) 
    {
        this.manager = manager;
    }

    public bool IsAuthorised(IHttpServerRequest httpRequest)
    {
        var claim = new Claim(httpRequest.PathToControllerAndMethod);
        Principal principal;
        if (httpRequest.HasAuthorisationHeader)
            principal = new AuthorisationPrincipal(httpRequest.AuthorisationHeaderValue); // or return 
        else
            principal = new AnonymousPrincipal();

        return manager.IsAuthorised(claim, principal);
    }
}
```

2. We take a Attribute based approach (but harder to refer to a single point of truth):
[UriFormat("/simpleparameter/{id}")]
[HMACAuthorizeAttribute()]
public IGetResponse GetWithServerRequest(int id, [FromBody]MyType complexObject, HttpServerRequest request)
```

Let me know what you guys think, open to suggestions.

**Comment by stevegg** [comment]
As per #65 there are good reasons to be able to access the Http Header (and other values) of the incoming request directly.  While in this case it makes sense to build authentication mechanisms into the platform it won't always make sense to try and build everything into the platform.

**Comment by tomkuijsten** [comment]
@Jark what's your main argument for not exposing the request? I still think it should be possible somehow to access all request information. If we would expose this,  #70 (CORS) will be possible too.

**Comment by Jark** [comment]
@tomkuijsten well I don't especially mind if you do want to expose the request somehow, but I think the reasons given (implementing authorisation headers, implementing CORS) are bad reasons.
These are features that are so ingrained in how rest servers are used that these should be handled by restup itself in one way or another.  

Also, exposing the request is kind of like exposing lower level abstractions at a higher level of abstraction. 

But, as I mentioned before, we can expose the request, but I would advocate to use some kind of interface to expose it to the controllers so we expose the minimum amount required, because we will have to lock that interface down and never modify it. (we might also have to move that interface to the contracts component).

**Comment by clough42** [comment]
@Jark, I hear the arguments about authorization, though I'm not sure it's the job of the REST framework to restrict how my application authorizes.  In my case, it is a very simple embedded device that can display a QR code for a remote control UI.  The client javascript hashes the endpoint URL, posted data, a timestamp and a secret (provided in the hash of the QR code URL) and provides the hash along with the timestamp as HTTP headers.  The server needs to verify the hash and check that the timestamp is reasonably current to prevent replay attacks.

This is a common A&A mechanism that establishes an equivalence between remote and physical access without requiring any configuration or TLS.

I think, though, that the application isn't really the point here.  You're hearing a request from a user to get access to the headers from the handler code.  I think you will be hard-pressed to find a REST framework that doesn't provide a way to do this.

I solved my immediate problem by passing the additional parameters in the message body, but that prevents me from hashing the entire body.  Passing these values in the header would be preferable.

**Comment by Jark** [comment]
@clough42

I understand that for you this is a really important feature, but we can't just accept / add any feature without thinking about the design. If we just add any feature without thinking we're going to end up with a slow rest server that is hard to use.

As I mentioned above, I do think we should have the ability to inspect the headers in the method for any use cases we haven't thought about yet. Tom's design seems like a good place, basically he is saying that we could have a parameter that is of a certain interface and we'll auto fill that when the method is callled.

If you want the feature added, feel free to do the work and raise a pull request. Let us know if you do, then we can tag you on this issue so that no one else starts doing it.

I've also added #77 as a way to deal with CORS and Authorisation in a more structured way.

**Comment by tomkuijsten** [comment]
I think we're all pretty much on the same page. I do want to allow extensibility, but don't want to implement specifics (like CORS). If we look at WCF, it doesn't support CORS out of the box, but you can easily implement it using a [message inspector](http://enable-cors.org/server_wcf.html). I think we should provide something like a message inspector, but that's exactly what @Jark is proposing in #77. I think we can close this issue and move the discussion to #77.

**Comment by Jark** [comment]
Agreed

**Comment by tomkuijsten** [comment]
Just created a new [branch](https://github.com/tomkuijsten/restup/tree/feature-message-inspectors) for this feaure.

**Comment by tomkuijsten** [comment]
Replaced by #87
