### ISSUE TITLE
OData support?

### ISSUE THREAD

**Issue by texanobta** [tomkuijsten/restup#97]
Is there any way, or idea on how, to expose an OData data provider through a restup controller?

**Comment by Jark** [comment]
You could approximate (most of) the OData protocol by creating rest controllers and returning / accepting responses in the correct formats, but it would require a few manual changes / parsing of OData query language. You might also need https://github.com/tomkuijsten/restup/issues/87 before you can return / receive all the OData headers.

There are currently no plans to implement OData as a built-in / tested feature since it is quite a complicated and extensive protocol (https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=odata).

**Comment by tomkuijsten** [comment]
I agree, not something we want to support out-of-the-box. I'll close the issue. @texanobta if you have questions when implementing this feature yourself, feel free to create another issue.
